/* ═══════════════════════════════════════════════════════════
   Screenshot library — shared helpers
   ═══════════════════════════════════════════════════════════
   Single source of truth: `assets/img/screenshots/manifest.json` declares every
   marketing screenshot (id, file, intrinsic size, alt/caption copy, which page
   uses it, and the capture recipe).

   index.html / deck.html reference a shot by id:

     <figure class="shot" data-shot="backlog-tree" data-state="placeholder">
       <img src="/assets/img/screenshots/backlog-tree.png?v=<SITE_VERSION>" ...>
       <figcaption>…</figcaption>
     </figure>

   `data-state` mirrors the manifest `status`:
     "placeholder" → the committed PNG is generated by make-screenshots.mjs and
                     the page only renders the caption card (the placeholder
                     raster is never displayed on the live site).
     "captured"    → a real screenshot is committed and rendered.

   Placeholder PNGs carry a `tEXt` marker, so placeholder-vs-real is verifiable
   without a decoder, a dependency, or any image tooling — same stdlib-only
   approach as the rest of this repo.
*/

import { deflateSync } from 'node:zlib';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const SHOTS_DIR = 'assets/img/screenshots';
export const SHOTS_HREF = '/assets/img/screenshots';
export const MANIFEST_PATH = join(ROOT, SHOTS_DIR, 'manifest.json');
export const GUIDE_PATH = join(ROOT, SHOTS_DIR, 'README.md');

/** tEXt keyword/value written into every generated placeholder PNG. */
export const MARKER_KEYWORD = 'ado-code-shot';
export const MARKER_VALUE = 'placeholder-v1';

/** Pages that may reference shots (`usedOn` values → file names). */
export const PAGES = { index: 'index.html', gallery: 'gallery.html', deck: 'deck.html' };

export const STATES = ['placeholder', 'captured'];
export const SHOT_ID_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
export const SHOT_FILE_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*\.png$/;

/* ── Manifest ─────────────────────────────────────────────── */

export function loadManifest(file = MANIFEST_PATH) {
  return JSON.parse(readFileSync(file, 'utf8'));
}

/**
 * Pure structural validation. Returns an array of human-readable problems
 * (empty array = valid).
 */
export function validateManifest(manifest) {
  const problems = [];
  if (!manifest || typeof manifest !== 'object' || Array.isArray(manifest)) {
    return ['manifest must be a JSON object'];
  }
  if (!Array.isArray(manifest.shots) || manifest.shots.length === 0) {
    return ['manifest.shots must be a non-empty array'];
  }

  const seen = new Set();
  manifest.shots.forEach((shot, i) => {
    if (!shot || typeof shot !== 'object') {
      problems.push('#' + i + ': shot must be an object');
      return;
    }
    const at = typeof shot.id === 'string' ? shot.id : '#' + i;

    if (typeof shot.id !== 'string' || !SHOT_ID_RE.test(shot.id)) {
      problems.push(at + ': id must be a kebab-case slug');
    } else if (seen.has(shot.id)) {
      problems.push(at + ': duplicate id');
    } else {
      seen.add(shot.id);
    }

    if (typeof shot.file !== 'string' || !SHOT_FILE_RE.test(shot.file)) {
      problems.push(at + ': file must be a kebab-case .png name');
    } else if (shot.file !== shot.id + '.png') {
      problems.push(at + ': file must be <id>.png (got ' + shot.file + ')');
    }

    for (const dim of ['width', 'height']) {
      const v = shot[dim];
      if (!Number.isInteger(v) || v < 320 || v > 5120) {
        problems.push(at + ': ' + dim + ' must be an integer between 320 and 5120');
      }
    }

    if (!STATES.includes(shot.status)) {
      problems.push(at + ': status must be one of ' + STATES.join(' | '));
    }

    for (const field of ['title', 'alt', 'caption', 'capture']) {
      const v = shot[field];
      if (typeof v !== 'string' || v.trim().length < 8) {
        problems.push(at + ': ' + field + ' must be a non-trivial string');
      }
    }

    if (typeof shot.alt === 'string') {
      if (/"/.test(shot.alt)) {
        problems.push(at + ': alt must not contain a double quote (it breaks the HTML attribute)');
      }
      if (/(screenshot|image|picture) of/i.test(shot.alt)) {
        problems.push(at + ': alt should describe the UI, not say "' + 'screenshot of"');
      }
    }

    if (!Array.isArray(shot.usedOn) || shot.usedOn.length === 0) {
      problems.push(at + ': usedOn must list at least one page (' + Object.keys(PAGES).join(', ') + ')');
    } else {
      if (new Set(shot.usedOn).size !== shot.usedOn.length) {
        problems.push(at + ': usedOn has duplicates');
      }
      for (const page of shot.usedOn) {
        if (!Object.prototype.hasOwnProperty.call(PAGES, page)) {
          problems.push(at + ': usedOn contains unknown page "' + page + '"');
        }
      }
    }
  });

  return problems;
}

/** Shots whose `usedOn` contains the given page key. */
export function shotsForPage(manifest, page) {
  return manifest.shots.filter((shot) => Array.isArray(shot.usedOn) && shot.usedOn.includes(page));
}

/* ── PNG reading (no decoder: IHDR + tEXt only) ───────────── */

const PNG_SIGNATURE = [137, 80, 78, 71, 13, 10, 26, 10];

/**
 * Minimal PNG walker: signature, IHDR dimensions and tEXt pairs.
 * Never throws — returns { valid: false, reason } for anything unexpected.
 */
export function readPngInfo(buffer) {
  if (!Buffer.isBuffer(buffer) || buffer.length < 8) {
    return { valid: false, reason: 'too small to be a PNG' };
  }
  if (PNG_SIGNATURE.some((byte, i) => buffer[i] !== byte)) {
    return { valid: false, reason: 'bad PNG signature' };
  }

  let offset = 8;
  let width = 0;
  let height = 0;
  const texts = {};
  const types = [];

  while (offset + 8 <= buffer.length) {
    const length = buffer.readUInt32BE(offset);
    const type = buffer.toString('latin1', offset + 4, offset + 8);
    const dataStart = offset + 8;
    if (length > buffer.length || dataStart + length > buffer.length) {
      return { valid: false, reason: 'truncated ' + type + ' chunk' };
    }
    types.push(type);

    if (type === 'IHDR') {
      if (length < 13) return { valid: false, reason: 'short IHDR' };
      width = buffer.readUInt32BE(dataStart);
      height = buffer.readUInt32BE(dataStart + 4);
    } else if (type === 'tEXt') {
      const raw = buffer.toString('latin1', dataStart, dataStart + length);
      const nul = raw.indexOf('\0');
      if (nul > 0) texts[raw.slice(0, nul)] = raw.slice(nul + 1);
    }

    offset = dataStart + length + 4;
    if (type === 'IEND') break;
  }

  if (!width || !height) return { valid: false, reason: 'no IHDR dimensions found' };
  return { valid: true, width, height, texts, types };
}

/** Returns the shot id baked into a generated placeholder PNG, else null. */
export function placeholderId(buffer) {
  const info = readPngInfo(buffer);
  if (!info.valid) return null;
  const value = info.texts[MARKER_KEYWORD];
  if (typeof value !== 'string' || !value.startsWith(MARKER_VALUE)) return null;
  return value.slice(MARKER_VALUE.length).replace(/^:/, '') || null;
}

export function isPlaceholderPng(buffer) {
  return placeholderId(buffer) !== null;
}

/* ── PNG writing (5x7 bitmap font + flat brand background) ── */

const GLYPH_W = 5;
const GLYPH_H = 7;
const GLYPH_GAP = 1;

/** 5x7 glyphs, one number per row, MSB = leftmost column. */
const GLYPHS = {
  ' ': [0, 0, 0, 0, 0, 0, 0],
  '-': [0, 0, 0, 31, 0, 0, 0],
  '.': [0, 0, 0, 0, 0, 0, 4],
  ',': [0, 0, 0, 0, 0, 4, 8],
  ':': [0, 4, 0, 0, 0, 4, 0],
  '/': [1, 2, 2, 4, 8, 8, 16],
  '#': [10, 31, 10, 10, 10, 31, 10],
  '+': [0, 4, 4, 31, 4, 4, 0],
  '(': [2, 4, 8, 8, 8, 4, 2],
  ')': [8, 4, 2, 2, 2, 4, 8],
  '!': [4, 4, 4, 4, 4, 0, 4],
  '?': [14, 17, 1, 2, 4, 0, 4],
  0: [14, 17, 19, 21, 25, 17, 14],
  1: [4, 12, 4, 4, 4, 4, 14],
  2: [14, 17, 1, 2, 4, 8, 31],
  3: [31, 2, 4, 2, 1, 17, 14],
  4: [2, 6, 10, 18, 31, 2, 2],
  5: [31, 16, 30, 1, 1, 17, 14],
  6: [6, 8, 16, 30, 17, 17, 14],
  7: [31, 1, 2, 4, 8, 8, 8],
  8: [14, 17, 17, 14, 17, 17, 14],
  9: [14, 17, 17, 15, 1, 2, 12],
  A: [14, 17, 17, 31, 17, 17, 17],
  B: [30, 17, 17, 30, 17, 17, 30],
  C: [14, 17, 16, 16, 16, 17, 14],
  D: [30, 17, 17, 17, 17, 17, 30],
  E: [31, 16, 16, 30, 16, 16, 31],
  F: [31, 16, 16, 30, 16, 16, 16],
  G: [14, 17, 16, 23, 17, 17, 15],
  H: [17, 17, 17, 31, 17, 17, 17],
  I: [14, 4, 4, 4, 4, 4, 14],
  J: [7, 2, 2, 2, 2, 18, 12],
  K: [17, 18, 20, 24, 20, 18, 17],
  L: [16, 16, 16, 16, 16, 16, 31],
  M: [17, 27, 21, 21, 17, 17, 17],
  N: [17, 25, 21, 19, 17, 17, 17],
  O: [14, 17, 17, 17, 17, 17, 14],
  P: [30, 17, 17, 30, 16, 16, 16],
  Q: [14, 17, 17, 17, 21, 18, 13],
  R: [30, 17, 17, 30, 20, 18, 17],
  S: [15, 16, 16, 14, 1, 1, 30],
  T: [31, 4, 4, 4, 4, 4, 4],
  U: [17, 17, 17, 17, 17, 17, 14],
  V: [17, 17, 17, 17, 17, 10, 4],
  W: [17, 17, 17, 21, 21, 27, 17],
  X: [17, 17, 10, 4, 10, 17, 17],
  Y: [17, 17, 10, 4, 4, 4, 4],
  Z: [31, 1, 2, 4, 8, 16, 31],
};

export function hasGlyph(char) {
  return Object.prototype.hasOwnProperty.call(GLYPHS, char);
}

/** Upper-cases and maps unknown characters (é, →, …) to '-' so text always renders. */
export function sanitizeLabel(text) {
  return String(text)
    .toUpperCase()
    .split('')
    .map((char) => (hasGlyph(char) ? char : '-'))
    .join('');
}

export function measureText(text, scale) {
  if (!text.length) return 0;
  return (text.length * (GLYPH_W + GLYPH_GAP) - GLYPH_GAP) * scale;
}

function fillRect(rgb, width, height, x, y, w, h, color) {
  const x0 = Math.max(0, Math.round(x));
  const y0 = Math.max(0, Math.round(y));
  const x1 = Math.min(width, Math.round(x + w));
  const y1 = Math.min(height, Math.round(y + h));
  for (let yy = y0; yy < y1; yy++) {
    for (let xx = x0; xx < x1; xx++) {
      const i = (yy * width + xx) * 3;
      rgb[i] = color[0];
      rgb[i + 1] = color[1];
      rgb[i + 2] = color[2];
    }
  }
}

export function drawText(rgb, width, height, text, x, y, scale, color) {
  String(text).split('').forEach((char, i) => {
    const rows = GLYPHS[char];
    if (!rows) return;
    const cx = x + i * (GLYPH_W + GLYPH_GAP) * scale;
    rows.forEach((row, r) => {
      for (let c = 0; c < GLYPH_W; c++) {
        if ((row >> (GLYPH_W - 1 - c)) & 1) {
          fillRect(rgb, width, height, cx + c * scale, y + r * scale, scale, scale, color);
        }
      }
    });
  });
}

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buffer) {
  let c = -1;
  for (let i = 0; i < buffer.length; i++) c = CRC_TABLE[(c ^ buffer[i]) & 0xff] ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

function pngChunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length, 0);
  const body = Buffer.concat([Buffer.from(type, 'latin1'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body), 0);
  return Buffer.concat([length, body, crc]);
}

/** Encodes raw RGB bytes as an 8-bit truecolour PNG. Pure + deterministic. */
export function encodePng({ width, height, rgb, texts = {} }) {
  const stride = width * 3;
  const raw = Buffer.alloc((stride + 1) * height);
  for (let y = 0; y < height; y++) {
    raw[y * (stride + 1)] = 0; // filter: none
    rgb.copy(raw, y * (stride + 1) + 1, y * stride, (y + 1) * stride);
  }

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 2; // colour type: truecolour
  ihdr[10] = 0; // deflate
  ihdr[11] = 0; // adaptive filtering
  ihdr[12] = 0; // no interlace

  const parts = [
    Buffer.from(PNG_SIGNATURE),
    pngChunk('IHDR', ihdr),
    pngChunk('IDAT', deflateSync(raw, { level: 9 })),
  ];
  for (const [keyword, value] of Object.entries(texts)) {
    parts.push(
      pngChunk(
        'tEXt',
        Buffer.concat([
          Buffer.from(String(keyword), 'latin1'),
          Buffer.from([0]),
          Buffer.from(String(value), 'latin1'),
        ])
      )
    );
  }
  parts.push(pngChunk('IEND', Buffer.alloc(0)));
  return Buffer.concat(parts);
}

const BG = [11, 14, 20];
const FRAME = [35, 42, 59];
const ACCENT = [43, 143, 224];
const INK = [230, 233, 240];
const DIM = [139, 147, 167];

/**
 * Renders the committed stand-in PNG for a shot: brand-dark plate, hairline
 * frame and the shot id, size and capture pointer. Carries the tEXt marker so
 * `placeholderId()` can prove it is not a real capture.
 */
export function placeholderPng({
  id,
  width = 1440,
  height = 900,
  note = 'CAPTURE GUIDE: ASSETS/IMG/SCREENSHOTS/README.MD',
}) {
  const rgb = Buffer.alloc(width * height * 3);
  fillRect(rgb, width, height, 0, 0, width, height, BG);

  const inset = Math.max(12, Math.round(width / 90));
  const edge = Math.max(2, Math.round(width / 480));
  fillRect(rgb, width, height, inset, inset, width - inset * 2, edge, FRAME);
  fillRect(rgb, width, height, inset, height - inset - edge, width - inset * 2, edge, FRAME);
  fillRect(rgb, width, height, inset, inset, edge, height - inset * 2, FRAME);
  fillRect(rgb, width, height, width - inset - edge, inset, edge, height - inset * 2, FRAME);

  const lines = [
    { text: 'PLACEHOLDER', scale: Math.max(4, Math.round(width / 144)), color: ACCENT },
    { text: sanitizeLabel(id), scale: Math.max(3, Math.round(width / 240)), color: INK },
    { text: sanitizeLabel(width + ' X ' + height + ' PNG'), scale: Math.max(2, Math.round(width / 360)), color: DIM },
    { text: sanitizeLabel(note), scale: Math.max(2, Math.round(width / 520)), color: DIM },
  ];

  const lineHeights = lines.map((line) => GLYPH_H * line.scale);
  const gap = Math.round(width / 120);
  const blockHeight = lineHeights.reduce((sum, h) => sum + h, 0) + gap * (lines.length - 1);

  let y = Math.round((height - blockHeight) / 2);
  lines.forEach((line, i) => {
    const text = String(line.text);
    const x = Math.max(0, Math.round((width - measureText(text, line.scale)) / 2));
    drawText(rgb, width, height, text, x, y, line.scale, line.color);
    y += lineHeights[i] + gap;
  });

  return encodePng({
    width,
    height,
    rgb,
    texts: { [MARKER_KEYWORD]: MARKER_VALUE + ':' + id },
  });
}

/* ── HTML scanning ────────────────────────────────────────── */

/**
 * Extracts every `<figure … data-shot="…">…</figure>` from a page: the wiring
 * the tests compare against the manifest.
 */
export function scanShotFigures(html) {
  const figures = [];
  const figureRe = /<figure\b([^>]*\bdata-shot="([^"]+)"[^>]*)>([\s\S]*?)<\/figure>/g;
  let match;
  while ((match = figureRe.exec(html)) !== null) {
    const [, attrs, id, body] = match;
    const imgRe = /<img\b([^>]*)>/.exec(body);
    const imgAttrs = imgRe ? imgRe[1] : null;
    const attr = (source, name) => {
      if (!source) return null;
      const found = new RegExp('\\b' + name + '="([^"]*)"').exec(source);
      return found ? found[1] : null;
    };
    figures.push({
      id,
      state: attr(attrs, 'data-state'),
      src: attr(imgAttrs, 'src'),
      alt: attr(imgAttrs, 'alt'),
      width: attr(imgAttrs, 'width'),
      height: attr(imgAttrs, 'height'),
      hasImg: Boolean(imgRe),
      caption: /<figcaption[^>]*>([\s\S]*?)<\/figcaption>/.exec(body)
        ? /<figcaption[^>]*>([\s\S]*?)<\/figcaption>/
            .exec(body)[1]
            .replace(/<[^>]+>/g, ' ')
            .replace(/\s+/g, ' ')
            .trim()
        : null,
    });
  }
  return figures;
}
